baseURL: https://www.mattjh.sh/
languageCode: en-us
title: mattjh blog
sitedescription: "Welcome to my space! My name is Mattias and this is where I share whatever i want!"

module:
  imports:
    - path: github.com/LordMathis/hugo-theme-nightfall

markup:
  highlight:
    style: "nord"

menu:
  header:
    - name: posts
      weight: 0
      url: post
    - name: whoami
      weight: 1
      url: whoami
    - name: cv
      weight: 3
      url: https://cv.mattjh.sh/
      hrefTargetBlank: true

params:
  author:
    name: Mattias Holmgren
    bio: "I build things"
  user: mattjh
  hostname: blog
  cloudFront:
    url: "https://d25ycjc5dtax3g.cloudfront.net"
    images: "https://d25ycjc5dtax3g.cloudfront.net/images"
    videos: "https://d25ycjc5dtax3g.cloudfront.net/videos"
    asciinema: "https://d25ycjc5dtax3g.cloudfront.net/asciinema"
  readingTime: false
  social:
    - key: 0
      name: github
      url: "https://github.com/mattjh1"
      icon: "fa-brands fa-github"
    - key: 1
      name: twitter
      url: "https://x.com/MattiasHolmgr"
      icon: "fa-brands fa-x-twitter"
    - key: 2
      name: linkedin
      url: "https://www.linkedin.com/in/mattias-holmgren-b2407714a/"
      icon: "fa-brands fa-linkedin"
    - key: 3
      name: email
      url: "mailto:me@mattjh.sh"
      icon: "fa-regular fa-envelope"
  customCSS:
    - "sass/main.scss"
  minify: true
  assets:
    cachedir: "resources/_gen"
